name: build

on: [push, pull_request]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: [3.8]
      fail-fast: false
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: dependencies
      shell: bash
      run: |
        python -mpip install -r requirements.txt

    - name: build
      shell: bash
      run: |
        make libs

    - name: test
      shell: bash
      run: |
        python -m pytest -vv lib

    - name: compare_algorithms
      shell: bash
      # TODO setup.py must be named setup.py to work with pip.
      # Either merge both libraries into a single library or
      # restructure the repo layout to allow all setup.py files
      # to be named setup.py .
      run: |
        python ./setup_gamma_approx.py develop
        python ./setup_hphmm.py develop
        python3 -m lib.testbed.main --seed 0xdecaff --n-problems 30

